var choiceE = {
	1:	[	["The young lady is a ...","teacher.","student.","Chinese."],
			["The student is ...","a man.","a woman.","an American."],
			["These 2 people ...","didn't know each other before.","knew each other before.","have the same last name."],
			["The teacher's last name is ...","Wang.","Peng.","Li."]
		],
	2:	[	["The photo belongs to ...","Little Wang.","Li You.","meimei."],
			["The person in the picture is ...","Little Wang's nephew.","Little Wang.","Little Wang's son."],
			["Little Wang has ...","an elder sister.","a younger brother.","a son."],
			["Little Wang's sister has ...","three sons.","two sons.","one son."]
		],
	3:	[	["Little Wang is __ this year.","nineteen","eighteen","seventeen"],
			["Miss Zhang is __ this year.","seventeen","eighteen","nineteen"],
			["Miss Zhang ...","will have dinner late.","will not have dinner today.","has already had dinner."],
			["Miss Zhang's birthday is ...","today.","November 6.","tomorrow."],
			["Little Wang's Birthday is ...","November 6.","today.","tomorrow."],
			["Li Ming has invited ...","Miss Zhang.","Little Wang.","both of them."]
		],
	4:	[	["This weekend is ...","lawyer Zhang's birthday.","this man's birthday.","this woman's birthday."],
			["To celebrate the birthday they will ...","go out for a dinner.","go to see a Chinese movie.","go to see an American movie."],
			["The man wants to see a movie ...","on Saturday.","now.","on Sunday."],
			["This man will take the woman ...","to see a Chinese movie.","to dinner.","to see an American movie."],
			["The woman thinks that ...","only Chinese movies are good.","all movies are boring.","American movies are interesting."]
		],
	5:	[	["Little Wang ...","often comes to visit my brother.","is my classmate.","often comes to visit me."],
			["Little Wang has ...","only brothers.","only sisters.","both brothers and sisters."],
			["Little Wang's mother, Mrs. Wang is a ...","doctor.","teacher.","lawyer."],
			["Mr. Wang and his children often ...","play ball.","visit my brother.","go out to eat."],
			["Yesterday was ...","Sunday.","Saturday.","Tuesday."],
			["Yesterday my brother ...","was with Little Wang's family.","went to see a doctor.","was invited to a dinner by Little Wang."],
			["Yesterday my brother didn't come home till ...","9:15.","8:15.","6:15."],
			["My mother wants to invite them ...","to have dinner with us.","to a movie.","to chat with us."]
		],
	6:	[	["Li You is looking for ...","Little Zhang.","her brother.","Little Gao."],
			["Little Gao will ...","invite Li You to dinner.","call Li You.","go to a meeting."],
			["Little Zhang will not be back until ...","7:30 PM.","7:00 PM.","next month."],
			["Li You wants to ...","practice Chinese.","have dinner with Zhang's family.","go to a meeting at school."],
			["Next month Li You will ...","go to China.","go to a meeting at school.","practice Chinese with Little Zhang."],
			["... are going to China","Li You and her brother.","Li You and Little Gao.","Little Zhang and his father."],
			["Li You will have dinner with _____ today","Little Gao.","her brother.","Little Zhang."]
		],
	7:	[	["Right now is ...","8:15 AM.","8 AM.","10 AM."],
			["Today Little Gao came to school ...","early.","late.","just before class."],
			["What did Little Gao do last night?","Entertained some friends.","Reviewed the grammar.","Prepared the new text."],
			["Little Zhang ...","introduced a few friends to Little Gao.","went to see Little Gao at midnight.","went to look for the teacher."],
			["The teacher asked Little Gao to _____ now.","go to see him","study","go home"],
			["The teacher told Little Gao that ...","today's grammar is a bit difficult.","there are not too many new words today.","there are a lot of grammar points today."],
			["The teacher is going to _____ now.","his office","Little Gao's house","the library"]
		],
	8:	[	["Last Sunday ...","Little Zhang studied.","they both studied.","Li You studied."],
			["Li You studied a little ...","on Saturday.","on Sunday.","on both days."],
			["Li You _____ at 11 AM on Sunday.","got up","had breakfast","had lunch"],
			["After lunch Li You ...","went to see Little Gao.","went home.","went to see Little Zhang."],
			["Li You didn't know Little Gao could speak ...","Japanese.","Chinese.","English."],
			["Last weekend Little Zhang studied a lot because ...","he will have an exam today.","he doesn't have any friends.","his pronounciation is not good enough."],
			["We think that Little Gao ...","speaks Japanese quite well.","doesn't pronounce Japanese well enough.","doesn't understand Japanese."]
		],
	9:	[	["Li You asked Little Wang to ...","go to a movie.","go to a concert.","go shopping with her."],
			["Little Wang was planning to _____ this afternoon","go shopping","go to a concert","go to Li You's house"],
			["Lawyer Zhang invited the Wang family ...","to a concert.","to a movie.","to dinner."],
			["Last month Little Wang bought a pair of _____ pants.","brown","yellow","black"],
			["Little Wang bought those pants with ...","Li You.","Lawyer Zhang.","his brother."],
			["Little Wang wants to ...","get a pair with a different color.","return the pants he bought.","get a pair with the same color."],
			["Li You asked Little Wang to ...","try on her brother's pants.","have lunch at her house.","buy a pair of brown pants."],
			["Little Wang is going to Li You's house ...","this afternoon.","tomorrow.","this morning."]
		],
	11:	[	["Little Ye was very busy ...","a while ago.","just now.","last night."],
			["... invited Little Li to go on a trip.","Mr. Zhang","Teacher Wang","Little Ye"],
			["They plan to go this ...","winter.","spring.","autumn."],
			["Why did Little Li come to see Little Ye?","To get information on Taiwan's weather.","To find out if he is busy.","To find out what kind of a person Mr. Zhang is."],
			["Taipei's winter is ...","colder than here.","warmer than here.","very warm."],
			["Little Ye panicked because ...","she didn't have warm clothes.","she didn't have clothes for warm weather.","her clothes were all small."],
			["Right after their conversation Little Li will ...","get Little Ye's clothes.","go to visit Teacher Wang.","go to Taipei."],
			["Little Li is ...","smaller than Little Ye.","taller than Little Ye.","bigger than Little Ye."]
		],
	10:	[	["Miss Wang will ...","go to the store before getting home.","go to visit Mr. Zhang now.","go to the store after getting home."],
			["Both Miss Wang and Mr. Zhang want to buy ...","something to drink.","some beer.","some cola."],
			["Miss Wang found riding a bus in China interesting because ...","you need to buy a ticket.","you can chat with the driver.","you can drink beer on the bus."],
			["Miss Wang liked taking ____ the best","a taxi","the bus","the subway"],
			["It is fun to take a taxi in China because ...","you can chat with the driver.","it is very fast.","you can drink beer in the taxi."],
			["Miss Wang said taking _____ is the fastest.","the subway.","the bus","a taxi"]
		],
	12:	[	["This man ordered ...","rice.","dumplings.","both rice an dumplings."],
			["He wanted some ...","beer.","cola.","water."],
			["He ordered ...","fish braised in soy sauce.","sweet and sour fish.","hot and sour fish."],
			["The waitress made a mistake on ...","everything.","one of the dishes.","the soup only."],
			["The reason she made the mistake was that ...","she brought over someone else's order.","she didn't hear clearly.","what he ordered was sold out."]
		],
	21:	[	["Little Wang got a tape from ...","the lab.","Japan.","Li Ming."],
			["The tape is in ___ now.","Japan","the lab","the kitchen"],
			["___ took the tape away.","Li Ming's brother","Li Ming","Little Wang"],
			["Li Ming's brother is interested in ...","learning Chinese.","learning Japanese.","their kitchen."],
			["The tape will definitely be back to the lab ...","after the due day.","on the due day.","before the due day."]
		],
	13:	[	["Li Xing is writing to his ...","teacher.","American friends.","Chinese friends."],
			["Li Xing is in _____ now.","China","Japan","US"],
			["Li Xing was eager to ...","make friends.","contact his old friends.","go home."],
			["His school is _____ Tian'anmen.","far from","near","at"],
			["Li Xing has been to Tian'anmen ...","Three times.","Twice.","once."]
		],
	14:	[	["Whose house did Little Li visit yesterday?","Miss Bai's.","Little Zhang's.","Miss Bai's boyfriend's."],
			["They both think that the puppy is ...","ugly.","too small.","pretty."],
			["Little Zhang thinks that the puppy's nose is ...","too big.","too small.","too short."],
			["The puppy's eyes are ...","too small.","too big.","beautiful."],
			["This puppy is ...","a present from Little Zhang.","purchased by Miss Bai's boyfriend.","purchased by Miss Bai."]
		],
	15:	[	["The teacher ...","will check our homework.","forgot to bring the character book.","asked them to hand in their homework."],
			["Little Zhang ...","forgot to bring his homework.","has gone home.","has brought out his homework."],
			["The class ...","has started already.","is over.","hasn't started yet."],
			["The teacher will accept their homework ...","before noon.","in class only.","before class only."],
			["Little Zhang will go home ...","after class.","at noon.","now."]
		],
	16:	[	["Miss Bai ...","found her medicine finally.","found the medicine for Little Li.","didn't find her medicine after all."],
			["Little Li ...","wasn't very helpful.","helped Miss Bai looking for the medicine.","tried to be very helpful."],
			["Miss Bai ...","will not take the medicine this time.","took too much of the medicine.","is seriously allergic to this medicine."],
			["Miss Bai ...","can't remember when she took the medicine last time.","keeps good record of her medicine intake.","didn't want to get up."]
		],
	17:	[	["Little Zhang has known Little Xie for ...","two months.","a month.","three months."],
			["Little Xie ...","has difficulty finding a place.","has found an apartment.","has decided not to move."],
			["Little Zhang ...","likes Little Xie.","doesn't know what to do.","wants to find an apartment."],
			["Little Zhang's apartment has ...","a bedroom and a living room.","a bedroom and no other rooms.","two bedrooms."],
			["If Little Xie moves in, they will each pay ...","less than $400.","less than $300.","$700."]
		],
	22:	[	["Miss Bai's mom is in ...","China.","the post office.","the bank."],
			["Miss Bai didn't know ...","the best way to send money to China.","how to send a register mail.","where the post office is."],
			["Little Wang thinks that wiring money from the bank is ...","much faster than sending a register mail.","the same as sending a register mail.","cheaper than sending a register mail."],
			["Which factor is more important to Miss Bai's decision?","time","money","location"],
			["Miss Bai is going ___ now.","to the bank","to the post office","home"]
		],
	18:	[	["Siwen's friend wants to ...","go swimming.","watch a football game.","play football."],
			["When the friend called, Siwen was ...","watching TV.","playing tennis.","sleeping."],
			["They haven't gone swimming for ...","two weeks.","a week.","a month."],
			["____ was drowned.","Little Bai's cousin","Siwen's cousin","Little Bai"],
			["Siwen wants to ___ now.","watch a game","go downstairs","watch a movie"]
		],
	19:	[	["Little Li will go to China ...","with Miss Wang.","with Miss Wang's sister.","with both Miss Wang and her sister."],
			["Little Li wants to decide the travelling date based on ...","Miss Wang's schedule.","his class schedule.","the flight information."],
			["They've decided to leave ...","at the beginning of June.","in December.","at the end of June."],
			["Little Li doesn't enjoy ...","travel alone.","talking.","planning for the trip."],
			["Their flight will take about ...","12 hours.","10 hours.","6 hours."]
		],
	23:	[	["Miss Wang's uncle lives in ___ now.","California","Washington","Shanghai"],
			["Miss Wang asks Little Li to ___ this weekend.","ski","help her uncle move","go to Shanghai"],
			["We know Miss Wang's uncle likes to ...","grow vegetables.","visit her.","ski."],
			["Little Li will go with Miss Wang because ...","he is free this weekend.","he wants to visit Mr. Wang.","he likes cucumber."],
			["Miss Wang showed Little Li ___ from her uncle.","a picture","some cucumbers","a letter"]
		],
	20:	[	["Xiao Ming is going to ...","study abroad.","visit his grandma.","visit his uncle."],
			["He's going to fly for ...","over 10 hours. (less than 20 hours)","over 10 hours. (less than 11 hours)","about 17 hours."],
			["His grandma wants him to take some __ with him.","dumplings","rice","water"],
			["Xiao Ming will be living ...","in the dormitory.","in an apartment.","with his uncle."],
			["How does Xiao Ming go to the airport?","He will take a taxi.","His uncle will take him there.","His grandma will take him there."]
		 ]
};

var choiceC = {
	1:	[],
	2:	[],
	3:	[],
	4:	[	["王小姐和她男朋友周末常","看电视。","听音乐。","去打球。"],
			["他们都不喜欢","唱歌。","打球。","看电影。"],
			["王小姐喜欢","看外国电影。","跳舞。","打球。"],
			["王小姐","有两个美国朋友。","有两个中国朋友。","没有别的朋友。"],
			["王小姐的男朋友","只吃美国饭。","觉得王小姐的美国朋友很有意思。","不喜欢打球。"],
			["李先生想请他们","去吃饭。","看电影。","去跳舞。"]
		],
	5:	[	["小王今天","去找小高了。","去喝咖啡了。","去图书馆了。"],
			["今天小王很高兴，因为","他认识了一个女孩子。","他不忙。","他喝了很多咖啡。"],
			["小王有一张___的照片。","李小姐","李友","小高"],
			["小王____才认识李小姐。","上个周末","下个周末","今天"],
			["小王想请李小姐","去听音乐。","去喝咖啡。","去唱歌。"],
			["李友的妹妹","很漂亮。","现在也在这儿。","今天才认识小高。"]
		],
	6:	[	["现在是","上午。","下午。","晚上。"],
			["高方是____的学生。","一年级","二年级","三年级"],
			["高方想去张老师的办公室","练习说中文。","问问题。","考试。"],
			["今天十二点半张老师要","去图书馆。","给学生考试。","帮高方练习中文。"],
			["张老师现在要","去办公室。","回家。","去图书馆。"],
			["今天张老师____吃饭。","十二点","十二点半","两点半"],
			["要是____，张老师就帮高方练习说中文。","张老师两点半以后有砍儿","高方请老师吃饭","高方不忙"]
		],
	7:	[],
	8:	[	["小妹给哥哥打电话的时候，哥哥正在","洗澡。","喝茶。","聊天儿。"],
			["今天小妹去找哥哥的时候，哥哥","已经起床了。","正在洗澡。","没起床。"],
			["现在他们要","一边聊天儿一边喝茶。","一边喝咖啡一边聊天儿。","一边听音乐一边喝茶。"],
			["谁给小妹介绍了一个新朋友？","张小姐","小王","哥哥"],
			["小王的专业是","电脑。","中文。","音乐。"],
			["小妹和小王什么时候在餐厅喝咖啡了？","昨天下午","昨天上午","明天晚上"],
			["明天晚上小王要","请小妹去听音乐。","给哥哥打电话。","请他们吃晚饭。"],
			["小妹请哥哥和小王聊天儿，因为","她想知道哥哥喜欢不喜欢小王。","哥哥很喜欢聊天儿。","哥哥想认识她们学校的学生。"]
		],
	9:	[	["小李_____在餐厅工作。","星期三，四点以后","星期三，十点以后","星期四，三点以后"],
			["小高除了报和茶以外，还要买","两瓶可乐。","两杯咖啡。","两瓶啤酒。"],
			["那儿的咖啡一杯","九毛了担","六毛九。","六毛了担"],
			["小李告诉小高，一共是","四块零三分。","两块八毛二。","五块钱。"],
			["小高想给小李","五块钱。","三分钱。","四块钱。"],
			["因为小李说他不可以不找钱，所以小高","要请小李喝咖啡。","很不高兴。","要在那儿工作。"]
		],
	11:	[	["王朋和李友___都在中国。","夏天","现在","秋天"],
			["李友在中国买了","几件衣服。","很多书。","一个录像。"],
			["李友在中国买了","玩儿得很高兴。","很想美国。","看了很多录像。"],
			["李友觉得中国的衣服","又好又便宜。","又贵又不舒服。","又热又闷。"],
			["小赴来看李友的时候，她正在","看录像。","开会。","买衣服。"],
			["李友在上海的时候，下雨下得","很多。","很大。","不多。"],
			["现在是","秋天。","夏天。","冬天。"],
			["上海现在比李友去的时候","舒服一点儿了。","热一点儿了。","更闷了。"]
		],
	10:	[	["今天是谁的生日？","叶小姐","叶小姐的哥哥","小张"],
			["新年的时候小张","会和姐姐在一起。","要去台北。","去看姐姐。"],
			["叶小姐什么时候要坐飞机？","寒假","这个星期","下个星期"],
			["叶小姐不知道","去机场怎么走。","机场在哪儿。","怎么去机场。"],
			["叶小姐去机场的时候","她会坐地铁。","她哥哥会送她去。","小张会送她去。"],
			["叶小姐不要哥哥送她，因为哥哥","开车开得不太好。","去台北了。","让她坐地铁。"]
		],
	12:	[],
	21:	[],
	13:	[],
	14:	[],
	15:	[],
	16:	[],
	17:	[],
	22:	[],
	18:	[],
	19:	[],
	23:	[],
	20:	[]
};
		
var truthE = {
	1:	[],
	2:	[],
	3:	[	[false,"Miss Wang treated Mr. Li last week."],
			[true,"Mr. Li cannot have dinner with Miss. Wang this Friday."],
			[false,"They decided to go on Saturday."],
			[true,"None of them is busy Sunday evening."],
			[true,"Mr. Li loves Chinese food."],
			[false,"They will meet at 7:15 PM."]
		],
	4:	[],
	5:	[],
	6:	[],
	7:	[	[true,"王先生星期天晚上来看我爸爸了。"],
			[true,"王先生说话说得很快，所以我不高兴。"],
			[false,"那天晚上我们学了一个中国歌儿。"],
			[false,"那天晚上我妹妹也在家。"],
			[true,"我说中文说得很快。"],
			[true,"我想请王先生教我写汉字。"],
			[true,"王先生唱歌唱得很快。"],
			[false,"我想我以后要常常陶录音。"]
		],
	8:	[],
	9:	[],
	11:	[],
	10:	[],
	12:	[],
	21:	[],
	13:	[],
	14:	[],
	15:	[],
	16:	[],
	17:	[],
	22:	[],
	18:	[],
	19:	[],
	23:	[],
	20:	[]
};

var truthC = {
	1:	[	[true,"李贵生是老师。"],
			[false,"李小姐也叫李贵生。"],
			[true,"李中美不是中国人。"],
			[false,"李老师是美国人。"]
		],
	2:	[	[false,"张老师的孩子都是大学生。"],
			[true,"张老师的孩子不都是女儿。"],
			[true,"张家有两个男孩子。"],
			[false,"张生的哥哥是老师。"],
			[false,"张生的妈妈是医生。"]
		],
	3:	[	[true,"姐姐请三个人吃晚饭。"],
			[false,"高友很喜欢小王。"],
			[false,"高友是我的同学。"],
			[true,"我不认识高友。"],
			[false,"我哥哥不认识高友。"],
			[true,"那三个人都是哥哥的同学。"]
		],
	4:	[	[false,"王思明想请小李去他哥哥家。"],
			[true,"王思明想去看电影。"],
			[true,"王思明的哥哥很喜欢《家∷这个电影。"],
			[false,"小李常常看外国电影。"],
			[true,"《家》是一个中国电影。"],
			[false,"他们明天晚上七点半去看这个电影。"]
		],
	5:	[	[true,"今天李友来我家了。"],
			[true,"今天我爸爸妈妈都不在家。"],
			[false,"小李是我哥哥的同学。"],
			[false,"我在学校的图书馆工作。"],
			[true,"今天我哥哥也在家。"],
			[false,"我请小李喝茶， 因为我们没有咖啡。"]
		],
	6:	[	[true,"小高现在没有时间聊天儿。"],
			[true,"小高昨天考了两个试。"],
			[false,"小高现在去图书馆看书，因为他今天不忙。"],
			[true,"小高很想认识张小姐的妹妹。"],
			[false,"昨天小高在张小姐家认识了她妹妹。"],
			[false,"张小姐想周末请小高去看电影。"],
			[true,"张小姐星期五晚上十点不在家。"],
			[true,"小高星期五晚上十一点以后要给张小姐打电话。"]
		],
	7:	[	[true,"王先生星期天晚上来看我爸爸了。"],
			[true,"王先生说话说得很快，所以我不高兴。"],
			[false,"那天晚上我们学了一个中国歌儿。"],
			[false,"那天晚上我妹妹也在家。"],
			[true,"我说中文说得很快。"],
			[true,"我想请王先生教我写汉字。"],
			[true,"王先生唱歌唱得很快。"],
			[false,"我想我以后要常常陶录音。"]
		],
	8:	[	[true," 现在小高在北京大学学习。"],
			[false,"今天下午李友要上电脑课。"],
			[false,"张老师很喜欢小高。"],
			[true,"李友觉得这个新老师说中文说得很清楚。"],
			[true,"李友和她的同学可以用电脑练习发音。"],
			[false,"李友觉得用电脑做萛课不太方便。"],
			[true,"李友的中文进步得很快，因为她常用电脑。"],
			[false,"李友希望小高用中文写日记。"]
		],
	9:	[	[false,"王朋和李友都很喜欢去看衣服。"],
			[true,"虽然李友很喜欢买东西，但是她不知道今天要买什么。"],
			[false,"王朋今天也去了，因为今天很多东西都很便宜。"],
			[false,"王朋的姐姐给王朋买了一件红衬衫。"],
			[true,"王朋觉得那件衬衫大小不合适。"],
			[false,"那儿的售货员都不认识李友。"],
			[true,"王朋要是不知道买什么东西，就不来这儿。"],
			[true,"今天王朋只想换一件衣服。"]
		],
	11:	[	[false,"李友请大家明天去她家。"],
			[true,"小张觉得下雨的时候不能看红叶。"],
			[true,"明天他们除了在小张家吃饭以外，还要看录像。"],
			[false,"明天王朋和李友都会去小张家。"],
			[false,"小张想知道李友什么时候去中国，因为他也想一起去。"],
			[true,"要是小张想买中国录像，就最好给王朋写信。"]
		],
	10:	[	[true,"王朋来找李友以前，小谢来了。"],
			[false,"小谢想今天下午自己去买鞋。"],
			[true,"小谢想坐公共汽车去，因为她和李友都没有汽车。"],
			[false,"坐公共汽车去太慢了。"],
			[true,"小谢去买鞋的时候要穿别的衣服。"],
			[true,"李友觉得和小谢一起去买东西会花太多时间。"],
			[false,"李友今天不想去买东西。"]
		],
	12:	[	[false,"小明觉得今天的茶好喝极了，所以还想喝。"],
			[false,"今天中午小明一个人去吃中餐了。"],
			[true,"小明很喜欢那家饭馆的牛肉。"],
			[true,"今天小明吃了午饭以后觉得很渴。"],
			[true,"小明觉得以后得少吃一点儿味精。"]
		],
	21:	[	[true,"小李现在在书店工作。"],
			[false,"小李在书店工作了三个星期了。"],
			[false,"小李很喜欢这个工作，因为他自己买书很便宜。"],
			[false,"小李每天都工作。"],
			[true,"小李每个星期工作十二个钟头。"]
		],
	13:	[],
	14:	[	[true,"李小姐昨天过生日。"],
			[false,"大家觉得李小姐做的鱼太酸了。"],
			[false,"我很喜欢喝李小姐买的汽水。"],
			[true,"我不会唱李小姐弹的歌。"],
			[true,"看见李小姐过生日，我自己也很想过生日。"]
		],
	15:	[	[true,"小王腿很疼，所以走路走得不快。"],
			[false,"小王看过一个医生，可是没有用。"],
			[false,"小王没有健康保险，所以不去看病。"],
			[true,"小王会请李小姐的爸爸给他看病。"],
			[false,"要是小王去看李医生，就得自己花钱。"]
		],
	16:	[	[true,"小谢觉得小王走得没有他快。"],
			[false,"小谢请小王跟他一起去打扫房间。"],
			[true,"小谢等小王，因为他不认识李老师的家。"],
			[true,"小王现在没有力气，所以不想走路。 "],
			[false,"小王今天打扫了八个钟头的房间。"]
		],
	17:	[	[false,"哥哥想找一个人跟他一起住。"],
			[true,"哥哥的房间现在没有人住。"],
			[true,"我想让小李租哥哥的房间。"],
			[true,"我知道小李不会很吵。"],
			[false,"租那个房间的人只要付房租和水电费。"],
			[true,"我不知道小李想不想来。"]
		],
	22:	[	[true,"以前我过生日的时候，我的男朋友都不记得。"],
			[false,"我觉得每年的生日都一样。"],
			[false,"今年我的男朋友又把我的生日忘了。"],
			[false,"我不知道红花是谁送我的。"],
			[true,"爸爸不但没有把我的生日忘了，而且还送我一百块钱。"]
		],
	18:	[	[false,"我买了一件新的运动服，因为我现在比以前胖了。"],
			[true,"哥哥把我的衣服借给小张了。"],
			[false,"小张穿我的衣服很合适。"],
			[true,"两天以前，我的运动服还在小张那儿。"],
			[true,"我觉得这种衣服很难买。"]
		],
	19:	[	[true,"我要坐的班机走得非常早。"],
			[false,"飞机会从这儿直飞韩国。"],
			[false,"我打算下个月去办签证。"],
			[false,"我买票的旅行社没有办签证的服务。"],
			[true,"我想少花十五块钱。"],
			[true,"我这次去韩国，可能不会有很多时间玩儿。"]
		],
	23:	[	[false,"北京开出租汽车的人就是导游。"],
			[true,"跟我聊天的这个人不住在城市里。"],
			[false,"这个开出租汽车的人觉得中国的政治和经济中心都在北京。"],
			[false,"这个开出租汽车的人住在北京的南边。"],
			[true,"这个开出租汽车的人很爱说话。"]
		],
	20:	[	[false,"小谢和她姐姐一起开车去麻州。"],
			[true,"小谢的机票在她的行李里边。"],
			[false,"小谢不知道机票在哪儿，所以哭了。"],
			[true,"小谢不用托运行李。"],
			[true,"小谢登机的时候飞机差不多要起飞了。"]
	]
};

var theMap = {
	1:	[],
	2:	[],
	3:	[],
	4:	[],
	5:	[],
	6:	[],
	7:	[],
	8:	[],
	9:	[],
	11:	[],
	10:	[],
	12:	[],
	21:	[],
	13:	[[4,"你要去什么地方？"]],
	14:	[],
	15:	[],
	16:	[],
	17:	[],
	22:	[],
	18:	[],
	19:	[],
	23:	[],
	20:	[]
};

var paragraph = {"ME": choiceE, "MC": choiceC, "TE": truthE, "TC": truthC, "TM": theMap};
