title: Integrated Chinese
email: krazete@gmail.com
description: >-
  Exercises for the UCI Chinese 1 course series.
  Originally from an old Berkeley website which only runs on IE.
url: "https://krazete.github.io"
baseurl: "/integrated-chinese"
github_username: krazete

# theme:
#   - minima
plugins:
  - jekyll-sitemap

# defaults:
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "default"
#       permalink: categories/:index/
#       exercises: ["word", "sentence", "paragraph"]

exclude:
  - old_things
  - static
  - webscraping
  - README.md
  - /*.py
