application: integrated-chinese
version: 4
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest # TODO: set an actual version number
- name: jinja2
  version: latest # TODO: set an actual version number

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- Assistance
- ^(.*/)?\.wav$

handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.app
