application: integrated-chinese
version: 69
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- Assistance
- ^(.*/)?\.wav$

handlers:
- url: /static
  static_dir: static
  application_readable: true
- url: /.*
  script: main.app
