application: integrated-chinese
version: 3
runtime: python27
api_version: 1
threadsafe: false

skip_files:
- ^(.*/)?\.wav$
- Assistance

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|mp3|ttf|otf|txt))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|mp3|ttf|otf|txt))

- url: .*
  script: main.py
