application: integrated-chinese
version: 4
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest # TODO: set an actual version number
- name: jinja2
  version: latest # TODO: set an actual version number

skip_files:
- ^(.*/)?\.wav$
- Assistance

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|mp3|ttf|otf|txt))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|mp3|ttf|otf|txt))

- url: .*
  script: main.app
