var choiceE = [
	[	["1311,The young lady is a ...","teacher.","student.","Chinese."],
		["1312,The student is ...","a man.","a woman.","an American."],
		["1313,These 2 people ...","didn't know each other before.","knew each other before.","have the same last name."],
		["1314,The teacher's last name is ...","Wang.","Peng.","Li."]
	],
	[	["2311,The photo belongs to ...","Little Wang.","Li You.","meimei."],
		["2312,The person in the picture is ...","Little Wang's nephew.","Little Wang.","Little Wang's son."],
		["2313,Little Wang has ...","an elder sister.","a younger brother.","a son."],
		["2314,Little Wang's sister has ...","three sons.","two sons.","one son."]
	],
	[	["3311,Little Wang is __ this year.","nineteen","eighteen","seventeen"],
		["3312,Miss Zhang is __ this year.","seventeen","eighteen","nineteen"],
		["3313,Miss Zhang ...","will have dinner late.","will not have dinner today.","has already had dinner."],
		["3314,Miss Zhang's birthday is ...","today.","November 6.","tomorrow."],
		["3315,Little Wang's Birthday is ...","November 6.","today.","tomorrow."],
		["3316,Li Ming has invited ...","Miss Zhang.","Little Wang.","both of them."]
	],
	[	["4311,This weekend is ...","lawyer Zhang's birthday.","this man's birthday.","this woman's birthday."],
		["4312,To celebrate the birthday they will ...","go out for a dinner.","go to see a Chinese movie.","go to see an American movie."],
		["4313,The man wants to see a movie ...","on Saturday.","now.","on Sunday."],
		["4314,This man will take the woman ...","to see a Chinese movie.","to dinner.","to see an American movie."],
		["4315,The woman thinks that ...","only Chinese movies are good.","all movies are boring.","American movies are interesting."]
	],
	[	["5311,Little Wang ...","often comes to visit my brother.","is my classmate.","often comes to visit me."],
		["5312,Little Wang has ...","only brothers.","only sisters.","both brothers and sisters."],
		["5313,Little Wang's mother, Mrs. Wang is a ...","doctor.","teacher.","lawyer."],
		["5314,Mr. Wang and his children often ...","play ball.","visit my brother.","go out to eat."],
		["5315,Yesterday was ...","Sunday.","Saturday.","Tuesday."],
		["5316,Yesterday my brother ...","was with Little Wang's family.","went to see a doctor.","was invited to a dinner by Little Wang."],
		["5317,Yesterday my brother didn't come home till ...","9:15.","8:15.","6:15."],
		["5318,My mother wants to invite them ...","to have dinner with us.","to a movie.","to chat with us."]
	],
	[	["6311,Li You is looking for ...","Little Zhang.","her brother.","Little Gao."],
		["6312,Little Gao will ...","invite Li You to dinner.","call Li You.","go to a meeting."],
		["6313,Little Zhang will not be back until ...","7:30 PM.","7:00 PM.","next month."],
		["6314,Li You wants to ...","practice Chinese.","have dinner with Zhang's family.","go to a meeting at school."],
		["6315,Next month Li You will ...","go to China.","go to a meeting at school.","practice Chinese with Little Zhang."],
		["6316,... are going to China","Li You and her brother.","Li You and Little Gao.","Little Zhang and his father."],
		["6317,Li You will have dinner with _____ today","Little Gao.","her brother.","Little Zhang."]
	],
	[	["7311,Right now is ...","8:15 AM.","8 AM.","10 AM."],
		["7312,Today Little Gao came to school ...","early.","late.","just before class."],
		["7313,What did Little Gao do last night?","Entertained some friends.","Reviewed the grammar.","Prepared the new text."],
		["7314,Little Zhang ...","introduced a few friends to Little Gao.","went to see Little Gao at midnight.","went to look for the teacher."],
		["7315,The teacher asked Little Gao to _____ now.","go to see him","study","go home"],
		["7316,The teacher told Little Gao that ...","today's grammar is a bit difficult.","there are not too many new words today.","there are a lot of grammar points today."],
		["7317,The teacher is going to _____ now.","his office","Little Gao's house","the library"]
	],
	[	["8311,Last Sunday ...","Little Zhang studied.","they both studied.","Li You studied."],
		["8312,Li You studied a little ...","on Saturday.","on Sunday.","on both days."],
		["8313,Li You _____ at 11 AM on Sunday.","got up","had breakfast","had lunch"],
		["8314,After lunch Li You ...","went to see Little Gao.","went home.","went to see Little Zhang."],
		["8315,Li You didn't know Little Gao could speak ...","Japanese.","Chinese.","English."],
		["8316,Last weekend Little Zhang studied a lot because ...","he will have an exam today.","he doesn't have any friends.","his pronounciation is not good enough."],
		["8317,We think that Little Gao ...","speaks Japanese quite well.","doesn't pronounce Japanese well enough.","doesn't understand Japanese."]
	],
	[	["9311,Li You asked Little Wang to ...","go to a movie.","go to a concert.","go shopping with her."],
		["9312,Little Wang was planning to _____ this afternoon","go shopping","go to a concert","go to Li You's house"],
		["9313,Lawyer Zhang invited the Wang family ...","to a concert.","to a movie.","to dinner."],
		["9314,Last month Little Wang bought a pair of _____ pants.","brown","yellow","black"],
		["9315,Little Wang bought those pants with ...","Li You.","Lawyer Zhang.","his brother."],
		["9316,Little Wang wants to ...","get a pair with a different color.","return the pants he bought.","get a pair with the same color."],
		["9317,Li You asked Little Wang to ...","try on her brother's pants.","have lunch at her house.","buy a pair of brown pants."],
		["9318,Little Wang is going to Li You's house ...","this afternoon.","tomorrow.","this morning."]
	],
	[	["a311,Little Ye was very busy ...","a while ago.","just now.","last night."],
		["a312,... invited Little Li to go on a trip.","Mr. Zhang","Teacher Wang","Little Ye"],
		["a313,They plan to go this ...","winter.","spring.","autumn."],
		["a314,Why did Little Li come to see Little Ye?","To get information on Taiwan's weather.","To find out if he is busy.","To find out what kind of a person Mr. Zhang is."],
		["a315,Taipei's winter is ...","colder than here.","warmer than here.","very warm."],
		["a316,Little Ye panicked because ...","she didn't have warm clothes.","she didn't have clothes for warm weather.","her clothes were all small."],
		["a317,Right after their conversation Little Li will ...","get Little Ye's clothes.","go to visit Teacher Wang.","go to Taipei."],
		["a318,Little Li is ...","smaller than Little Ye.","taller than Little Ye.","bigger than Little Ye."]
	],
	[	["b311,Miss Wang will ...","go to the store before getting home.","go to visit Mr. Zhang now.","go to the store after getting home."],
		["b312,Both Miss Wang and Mr. Zhang want to buy ...","something to drink.","some beer.","some cola."],
		["b313,Miss Wang found riding a bus in China interesting because ...","you need to buy a ticket.","you can chat with the driver.","you can drink beer on the bus."],
		["b314,Miss Wang liked taking ____ the best","a taxi","the bus","the subway"],
		["b315,It is fun to take a taxi in China because ...","you can chat with the driver.","it is very fast.","you can drink beer in the taxi."],
		["b316,Miss Wang said taking _____ is the fastest.","the subway.","the bus","a taxi"]
	],
	[	["12p1.1,This man ordered ...","rice.","dumplings.","both rice an dumplings."],
		["12p1.2,He wanted some ...","beer.","cola.","water."],
		["12p1.3,He ordered ...","fish braised in soy sauce.","sweet and sour fish.","hot and sour fish."],
		["12p1.4,The waitress made a mistake on ...","everything.","one of the dishes.","the soup only."],
		["12p1.5,The reason she made the mistake was that ...","she brought over someone else's order.","she didn't hear clearly.","what he ordered was sold out."]
	],
	[	["13p1.1,Little Wang got a tape from ...","the lab.","Japan.","Li Ming."],
		["13p1.2,The tape is in ___ now.","Japan","the lab","the kitchen"],
		["13p1.3,___ took the tape away.","Li Ming's brother","Li Ming","Little Wang"],
		["13p1.4,Li Ming's brother is interested in ...","learning Chinese.","learning Japanese.","their kitchen."],
		["13p1.5,The tape will definitely be back to the lab ...","after the due day.","on the due day.","before the due day."]
	],
	[	["14p1.1,Li Xing is writing to his ...","teacher.","American friends.","Chinese friends."],
		["14p1.2,Li Xing is in _____ now.","China","Japan","US"],
		["14p1.3,Li Xing was eager to ...","make friends.","contact his old friends.","go home."],
		["14p1.4,His school is _____ Tian'anmen.","far from","near","at"],
		["14p1.5,Li Xing has been to Tian'anmen ...","Three times.","Twice.","once."]
	],
	[	["15p1.1,Whose house did Little Li visit yesterday?","Miss Bai's.","Little Zhang's.","Miss Bai's boyfriend's."],
		["15p1.2,They both think that the puppy is ...","ugly.","too small.","pretty."],
		["15p1.3,Little Zhang thinks that the puppy's nose is ...","too big.","too small.","too short."],
		["15p1.4,The puppy's eyes are ...","too small.","too big.","beautiful."],
		["15p1.5,This puppy is ...","a present from Little Zhang.","purchased by Miss Bai's boyfriend.","purchased by Miss Bai."]
	],
	[	["16p1.1,The teacher ...","will check our homework.","forgot to bring the character book.","asked them to hand in their homework."],
		["16p1.2,Little Zhang ...","forgot to bring his homework.","has gone home.","has brought out his homework."],
		["16p1.3,The class ...","has started already.","is over.","hasn't started yet."],
		["16p1.4,The teacher will accept their homework ...","before noon.","in class only.","before class only."],
		["16p1.5,Little Zhang will go home ...","after class.","at noon.","now."]
	],
	[	["17p1.1,Miss Bai ...","found her medicine finally.","found the medicine for Little Li.","didn't find her medicine after all."],
		["17p1.2,Little Li ...","wasn't very helpful.","helped Miss Bai looking for the medicine.","tried to be very helpful."],
		["17p1.3,Miss Bai ...","will not take the medicine this time.","took too much of the medicine.","is seriously allergic to this medicine."],
		["17p1.4,Miss Bai ...","can't remember when she took the medicine last time.","keeps good record of her medicine intake.","didn't want to get up."]
	],
	[	["18p1.1,Little Zhang has known Little Xie for ...","two months.","a month.","three months."],
		["18p1.2,Little Xie ...","has difficulty finding a place.","has found an apartment.","has decided not to move."],
		["18p1.3,Little Zhang ...","likes Little Xie.","doesn't know what to do.","wants to find an apartment."],
		["18p1.4,Little Zhang's apartment has ...","a bedroom and a living room.","a bedroom and no other rooms.","two bedrooms."],
		["18p1.5,If Little Xie moves in, they will each pay ...","less than $400.","less than $300.","$700."]
	],
	[	["19p1.1,Miss Bai's mom is in ...","China.","the post office.","the bank."],
		["19p1.2,Miss Bai didn't know ...","the best way to send money to China.","how to send a register mail.","where the post office is."],
		["19p1.3,Little Wang thinks that wiring money from the bank is ...","much faster than sending a register mail.","the same as sending a register mail.","cheaper than sending a register mail."],
		["19p1.4,Which factor is more important to Miss Bai's decision?","time","money","location"],
		["19p1.5,Miss Bai is going ___ now.","to the bank","to the post office","home"]
	],
	[	["20p1.1,Siwen's friend wants to ...","go swimming.","watch a football game.","play football."],
		["20p1.2,When the friend called, Siwen was ...","watching TV.","playing tennis.","sleeping."],
		["20p1.3,They haven't gone swimming for ...","two weeks.","a week.","a month."],
		["20p1.4,____ was drowned.","Little Bai's cousin","Siwen's cousin","Little Bai"],
		["20p1.5,Siwen wants to ___ now.","watch a game","go downstairs","watch a movie"]
	],
	[	["21p1.1,Little Li will go to China ...","with Miss Wang.","with Miss Wang's sister.","with both Miss Wang and her sister."],
		["21p1.2,Little Li wants to decide the travelling date based on ...","Miss Wang's schedule.","his class schedule.","the flight information."],
		["21p1.3,They've decided to leave ...","at the beginning of June.","in December.","at the end of June."],
		["21p1.4,Little Li doesn't enjoy ...","travel alone.","talking.","planning for the trip."],
		["21p1.5,Their flight will take about ...","12 hours.","10 hours.","6 hours."]
	],
	[	["22p1.1,Miss Wang's uncle lives in ___ now.","California","Washington","Shanghai"],
		["22p1.2,Miss Wang asks Little Li to ___ this weekend.","ski","help her uncle move","go to Shanghai"],
		["22p1.3,We know Miss Wang's uncle likes to ...","grow vegetables.","visit her.","ski."],
		["22p1.4,Little Li will go with Miss Wang because ...","he is free this weekend.","he wants to visit Mr. Wang.","he likes cucumber."],
		["22p1.5,Miss Wang showed Little Li ___ from her uncle.","a picture","some cucumbers","a letter"]
	],
	[	["23p1.1,Xiao Ming is going to ...","study abroad.","visit his grandma.","visit his uncle."],
		["23p1.2,He's going to fly for ...","over 10 hours. (less than 20 hours)","over 10 hours. (less than 11 hours)","about 17 hours."],
		["23p1.3,His grandma wants him to take some __ with him.","dumplings","rice","water"],
		["23p1.4,Xiao Ming will be living ...","in the dormitory.","in an apartment.","with his uncle."],
		["23p1.5,How does Xiao Ming go to the airport?","He will take a taxi.","His uncle will take him there.","His grandma will take him there."]
	]
];