var truthE = [
	[],
	[],
	[	"3321,f,Miss Wang treated Mr. Li last week.",
		"3322,t,Mr. Li cannot have dinner with Miss. Wang this Friday.",
		"3323,f,They decided to go on Saturday.",
		"3324,t,None of them is busy Sunday evening.",
		"3325,t,Mr. Li loves Chinese food.",
		"3326,f,They will meet at 7:15 PM."
	],
	[],
	[],
	[],
	[	"7321,t,王先生星期天晚上来看我爸爸了。",
		"7322,t,王先生说话说得很快，所以我不高兴。",
		"7323,f,那天晚上我们学了一个中国歌儿。",
		"7324,f,那天晚上我妹妹也在家。",
		"7325,t,我说中文说得很快 。",
		"7326,t,我想请王先生教我写汉字。",
		"7327,t,王先生唱歌唱得很快。",
		"7328,f,我想我以后要常常陶录音。"
	],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[]
];